[package]
name = "relabs"
version = "0.2.0"
edition = "2024"
description = "Type-safe relative/absolute path wrappers."
license = "MIT"
repository = "https://github.com/fbinkert/relabs"

[dependencies]
